name: compiled_mustache
description: Native support for pre-compiled mustache templates
author: thislooksfun <thislooksfun@repbot.com>
homepage: https://github.com/thislooksfun/compiled_mustache
version: 1.0.0-beta1
dev_dependencies:
  test: "^0.12.27"