name: "compiled_mustache"
description: "Native support for pre-compiled mustache templates"
author: "thislooksfun <thislooksfun@repbot.com>"
homepage: "https://github.com/thislooksfun/compiled_mustache"
version: "1.0.1"
dev_dependencies:
  test: "^0.12.27"
  benchmark_harness: ">=1.0.0 <2.0.0"
  grinder: "^0.8.0"
  mustache4dart: "^2.1.0"
  yaml: "^2.1.13"
  path: "^1.5.0"